### ISSUE TITLE
Peer review comments

### ISSUE THREAD

**Issue by jeffgebhardt** [PeterBreen/portfolio-website#5]
Peter, this looks really good! I am loving the color scheme, going to have to check out that adobe color generator myself. Finding good looking colors is always one of the hardest parts for me.

The site is very responsive and looks good on both mobile/desktop.

The only 'bug' I noticed was that on mobile, the nav menu did not automatically hide after touching a link. Would it be a good idea to add some code to fade away the nav menu after a user touches a link? That way it prevents them from having to perform another action to view the page?

Keep up the good work!

**Comment by PeterBreen** [comment]
Fixed (sort of) by making a fixed mobile nav instead. See pull #6 

thanks for the feedback!
